apiVersion: v1
kind: Namespace
metadata:
  name: berhot-platform
  labels:
    app.kubernetes.io/part-of: berhot
    tier: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-commerce
  labels:
    app.kubernetes.io/part-of: berhot
    tier: commerce
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-experience
  labels:
    app.kubernetes.io/part-of: berhot
    tier: experience
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-engagement
  labels:
    app.kubernetes.io/part-of: berhot
    tier: engagement
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-workforce
  labels:
    app.kubernetes.io/part-of: berhot
    tier: workforce
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-ecosystem
  labels:
    app.kubernetes.io/part-of: berhot
    tier: ecosystem
---
apiVersion: v1
kind: Namespace
metadata:
  name: berhot-monitoring
  labels:
    app.kubernetes.io/part-of: berhot
    tier: monitoring
