apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-access
  namespace: berhot-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/berhot-identity-access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-management
  namespace: berhot-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pos-engine
  namespace: berhot-commerce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loyalty
  namespace: berhot-experience
